# Generated by Django 6.0.2 on 2026-02-20 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='food_images/'),
            preserve_default=False,
        ),
    ]
